pipeline {
  agent any

  environment {
    APP_DIR = "backend"
    IMAGE_NAME = "pdf-chat-backend"
    CONTAINER_NAME = "pdf-backend-test"
  }

  stages {
    stage('Checkout Code') {
      steps {
        git branch: 'feature/api-setup', url: 'https://github.com/Sarath-koparla/Pdf-chat-app.git'
      }
    }

    stage('Build Docker Image') {
      steps {
        dir("${APP_DIR}") {
          script {
            echo "Building Docker image..."
            sh 'docker build -t $IMAGE_NAME .'
          }
        }
      }
    }

    stage('Run Container (Test)') {
      steps {
        script {
          echo "Running Docker container (may fail if code not ready)..."
          sh '''
            docker run -d --rm -p 8000:8000 --name $CONTAINER_NAME $IMAGE_NAME || true
            sleep 5
            curl -f http://localhost:8000/docs || echo "App not ready yet"
          '''
        }
      }
    }
  }

  post {
    always {
      echo "Cleaning up..."
      sh 'docker rm -f $CONTAINER_NAME || true'
    }
  }
}
